on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      revery_release_created: ${{ steps.release.outputs['crates/revery--release_created'] }}
      revery_onion_release_created: ${{ steps.release.outputs['crates/revery-onion--release_created'] }}
      app_release_created: ${{ steps.release.outputs['packages/app--release_created'] }}
      revery_version: ${{ steps.release.outputs['crates/revery--version'] }}
      revery_onion_version: ${{ steps.release.outputs['crates/revery-onion--version'] }}
      app_version: ${{ steps.release.outputs['packages/app--version'] }}
      revery_tag: ${{ steps.release.outputs['crates/revery--tag_name'] }}
      revery_onion_tag: ${{ steps.release.outputs['crates/revery-onion--tag_name'] }}
      app_tag: ${{ steps.release.outputs['packages/app--tag_name'] }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
  publish-revery:
    needs: release-please
    if: needs.release-please.outputs.revery_release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "./crates/revery -> target"
      - working-directory: crates/revery
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish-revery-onion:
    needs: release-please
    if: needs.release-please.outputs.revery_onion_release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "./crates/revery-onion -> target"
      - working-directory: crates/revery-onion
        run: |
          cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  release-app:
    needs: release-please
    if: needs.release-please.outputs.app_release_created == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf  xdg-utils
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "./packages/app/src-tauri -> target"
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - working-directory: packages/app
        run: npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: packages/app
          tagName: ${{ needs.release-please.outputs.app_tag }}
          releaseName: "Revery v${{ needs.release-please.outputs.app_version }}"
          releaseBody: "See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/packages/app/CHANGELOG.md) for details."
          includeRelease: true
          args: ${{ matrix.args }}
